name: Init Terraform
description: Install Terraform and run terraform init

inputs:
  tf_directory:
    required: true
    description: "The directory in the repository with containing the terraform root module."
  credentials_json:
    required: true
    description: The credentials json file for the service account.

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.9
    
    - id: 'gcp-auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ inputs.credentials_json }}'

    - name: Terraform Init
      run: cd ${{ inputs.tf_directory }} && terraform init
      shell: bash